version: '3'

services:
  php:
    depends_on:
      - mysql
    image: php:8.1-apache
    build:
      context: php
    ports:
      - 80:80
      - 443:443
    volumes:
    - ./app:/var/www/html
    networks:
      - lamp-docker
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: lamp_docker
      MYSQL_USER: lamp_docker
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./databases/mysql:/var/lib/mysql
    networks:
      - lamp-docker
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - lamp-docker
networks:
  lamp-docker:
    driver: bridge
